### ISSUE TITLE
p2w-terra-relay: Re-evaluate retry logic/multi-message relaying

### ISSUE THREAD

**Issue by drozdziak1** [pyth-network/pyth2wormhole#99]
Currently, the generic relayer logic handles retries on whole arrays of VAAs. This is a problem, because it prevents the chain-specific bottom half from efficiently retrying only the things that have failed without doubling the generic part's work.

From a design POV we might want to put handling multiple batches and retries in a single place - either the generic `Relay.relay()` caller half, or the chain-specific `SomechainRelay.relay()` body. 

Both options appear to remove the corner cases and come with their pros and cons.

**Comment by ali-bahjati** [comment]
we won't have relayer anymore.
